# madeiracloud/scribe:centos6
# VERSION 2015.11.21

FROM madeiracloud/scribe:centos6-optimized
MAINTAINER Jimmy Xu<xjimmyshcn@gmail.com>

WORKDIR /root/

# Port
EXPOSE 1463

# set env
ENV LD_LIBRARY_PATH /usr/local/lib

VOLUME /visualops

